import 'package:flutter/material.dart';

/* Rectangle back 4
    Autogenerated by FlutLab FTF Generator
  */
class Back4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(50.0),
      child: Container(
        width: 466.0,
        height: 830.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(50.0),
          image: DecorationImage(
            image: ExactAssetImage(
              "assets/images/2e1404f5f0c30764a9c2890fec4d371f905debbd.png",
            ),
            fit: BoxFit.cover,
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(50.0),
          child: Image.asset(
            "assets/images/2e1404f5f0c30764a9c2890fec4d371f905debbd.png",
            color: null,
            fit: BoxFit.cover,
            width: 466.0,
            height: 830.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    );
  }
}
