import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector box1
    Autogenerated by FlutLab FTF Generator
  */
class Box1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/TipsWidget'),
      child: Container(
        width: 158.0,
        height: 68.0,
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(63, 0, 0, 0),
              offset: Offset(0.0, 4.0),
              blurRadius: 4.0,
            )
          ],
        ),
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0 20C0 8.9543 8.95431 0 20 0L138 0C149.046 0 158 8.95431 158 20L158 48C158 59.0457 149.046 68 138 68L20 68C8.9543 68 0 59.0457 0 48L0 20Z')
            ..color = Color.fromARGB(255, 247, 6, 136),
        ]),
      ),
    );
  }
}
