import 'package:flutter/material.dart';

/* Text Check BMI
    Autogenerated by FlutLab FTF Generator
  */
class CheckBMIWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Check BMI''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 22.0,
        fontFamily: 'SeoulNamsan',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
