import 'package:flutter/material.dart';

/* Text Doctor Tips
    Autogenerated by FlutLab FTF Generator
  */
class DoctorTipsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/TipsWidget'),
      child: Text(
        '''Doctor Tips''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 22.0,
          fontFamily: 'SeoulNamsan',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 255, 255, 255),
          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
