import 'package:flutter/material.dart';

/* Rectangle nurseee 1
    Autogenerated by FlutLab FTF Generator
  */
class Nurseee1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 247.0,
      height: 320.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/19f3db910699381fb69fd0de22ed623ffd52a6b2.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/19f3db910699381fb69fd0de22ed623ffd52a6b2.png",
          color: null,
          fit: BoxFit.cover,
          width: 247.0,
          height: 320.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
