import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined2b8d/widgets/EvaarrowiosbackfillWidget8.dart';

/* Frame bmicalci
    Autogenerated by FlutLab FTF Generator
  */
class Undefined2b8d extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: 5.0,
            top: 12.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: EvaarrowiosbackfillWidget8(),
          )
        ]),
      ),
    ));
  }
}
