import 'package:flutter/material.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Box8Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Ut1Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Eye1Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Box2Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/EarNoseThroatWidget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Box6Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Download1Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Box7Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/WomenhealthWidget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/HeartWidget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Rectangle23Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/VaccinesWidget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Box5Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/EvaarrowiosbackfillWidget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Box9Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/DOCTORSTIPSWidget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Va1Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/EyesWidget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Back1Widget.dart';
import 'package:flutterapp/figma/tipswidget/widgets/Cardido1Widget.dart';

/* Frame tips
    Autogenerated by FlutLab FTF Generator
  */
class TipsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 180, 182, 226),
            ),
            child: null,
          ),
          Positioned(
            left: -96.0,
            top: -56.0,
            right: null,
            bottom: null,
            width: 515.0,
            height: 714.0,
            child: Back1Widget(),
          ),
          Positioned(
            left: 5.0,
            top: 12.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: EvaarrowiosbackfillWidget(),
          ),
          Positioned(
            left: 20.0,
            top: 142.0,
            right: null,
            bottom: null,
            width: 316.0,
            height: 380.0,
            child: Rectangle23Widget(),
          ),
          Positioned(
            left: 62.0,
            top: 435.0,
            right: null,
            bottom: null,
            width: 234.0,
            height: 48.0,
            child: Box9Widget(),
          ),
          Positioned(
            left: 62.0,
            top: 366.0,
            right: null,
            bottom: null,
            width: 238.0,
            height: 48.0,
            child: Box8Widget(),
          ),
          Positioned(
            left: 249.0,
            top: 366.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 51.0,
            child: Download1Widget(),
          ),
          Positioned(
            left: 62.0,
            top: 301.0,
            right: null,
            bottom: null,
            width: 238.0,
            height: 47.0,
            child: Box6Widget(),
          ),
          Positioned(
            left: 62.0,
            top: 242.0,
            right: null,
            bottom: null,
            width: 238.0,
            height: 47.0,
            child: Box7Widget(),
          ),
          Positioned(
            left: 74.0,
            top: 252.0,
            right: null,
            bottom: null,
            width: 128.0,
            height: 23.0,
            child: WomenhealthWidget(),
          ),
          Positioned(
            left: 74.0,
            top: 314.0,
            right: null,
            bottom: null,
            width: 149.0,
            height: 26.0,
            child: EyesWidget(),
          ),
          Positioned(
            left: 74.0,
            top: 376.0,
            right: null,
            bottom: null,
            width: 175.0,
            height: 26.0,
            child: EarNoseThroatWidget(),
          ),
          Positioned(
            left: 249.0,
            top: 242.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 47.0,
            child: Ut1Widget(),
          ),
          Positioned(
            left: 62.0,
            top: 186.0,
            right: null,
            bottom: null,
            width: 238.0,
            height: 44.0,
            child: Box5Widget(),
          ),
          Positioned(
            left: 74.0,
            top: 192.0,
            right: null,
            bottom: null,
            width: 149.0,
            height: 26.0,
            child: HeartWidget(),
          ),
          Positioned(
            left: 249.0,
            top: 186.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 44.0,
            child: Cardido1Widget(),
          ),
          Positioned(
            left: 300.0,
            top: 301.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 47.0,
            child: Eye1Widget(),
          ),
          Positioned(
            left: 249.0,
            top: 435.0,
            right: null,
            bottom: null,
            width: 47.0,
            height: 48.0,
            child: Va1Widget(),
          ),
          Positioned(
            left: 74.0,
            top: 447.0,
            right: null,
            bottom: null,
            width: 149.0,
            height: 26.0,
            child: VaccinesWidget(),
          ),
          Positioned(
            left: 84.5,
            top: 37.0,
            right: null,
            bottom: null,
            width: 178.0,
            height: 74.0,
            child: Box2Widget(),
          ),
          Positioned(
            left: 103.0,
            top: 61.0,
            right: null,
            bottom: null,
            width: 149.0,
            height: 26.0,
            child: DOCTORSTIPSWidget(),
          )
        ]),
      ),
    ));
  }
}
