import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector box3
    Autogenerated by FlutLab FTF Generator
  */
class Box3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 268.0,
      height: 85.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 20C0 8.95431 8.9543 0 20 0L248 0C259.046 0 268 8.95431 268 20L268 65C268 76.0457 259.046 85 248 85L20 85C8.9543 85 0 76.0457 0 65L0 20Z')
          ..color = Color.fromARGB(255, 247, 26, 6),
      ]),
    );
  }
}
