import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector box4
    Autogenerated by FlutLab FTF Generator
  */
class Box4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefinedb1e2'),
      child: Container(
        width: 175.0,
        height: 71.0,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0 20C0 8.9543 8.95431 0 20 0L155 0C166.046 0 175 8.95431 175 20L175 51C175 62.0457 166.046 71 155 71L20 71C8.9543 71 0 62.0457 0 51L0 20Z')
            ..color = Color.fromARGB(255, 205, 123, 182),
        ]),
      ),
    );
  }
}
