import 'package:flutter/material.dart';

/* Text Call for help
    Autogenerated by FlutLab FTF Generator
  */
class CallforhelpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefined5694'),
      child: Text(
        '''Call for help''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 28.0,
          fontFamily: 'SeoulNamsan',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 0, 0, 0),
          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
