import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector cfh
    Autogenerated by FlutLab FTF Generator
  */
class CfhWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefined5694'),
      child: Container(
        width: 175.0,
        height: 73.0,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0 20C0 8.95431 8.95431 0 20 0L155 0C166.046 0 175 8.95431 175 20L175 53C175 64.0457 166.046 73 155 73L20 73C8.9543 73 0 64.0457 0 53L0 20Z')
            ..color = Color.fromARGB(255, 246, 136, 129),
        ]),
      ),
    );
  }
}
