import 'package:flutter/material.dart';

/* Rectangle emergency 1
    Autogenerated by FlutLab FTF Generator
  */
class Emergency1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 42.0,
      height: 32.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/84a30b59076225bcd81f75d1530fb97113a94689.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/84a30b59076225bcd81f75d1530fb97113a94689.png",
          color: null,
          fit: BoxFit.cover,
          width: 42.0,
          height: 32.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
