import 'package:flutter/material.dart';

/* Text EMERGENCY
    Autogenerated by FlutLab FTF Generator
  */
class EMERGENCYWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''EMERGENCY''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 26.0,
        fontFamily: 'SeoulNamsan',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
