import 'package:flutter/material.dart';

/* Text General
    Autogenerated by FlutLab FTF Generator
  */
class GeneralWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefinedb1e2'),
      child: Text(
        '''General''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 28.0,
          fontFamily: 'SeoulNamsan',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 3, 3, 3),
          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
