import 'package:flutter/material.dart';

/* Rectangle nurse 1
    Autogenerated by FlutLab FTF Generator
  */
class Nurse1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 166.0,
      height: 190.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/8c4dee042305e55f9a760d73801f778fe6f8daab.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/8c4dee042305e55f9a760d73801f778fe6f8daab.png",
          color: null,
          fit: BoxFit.cover,
          width: 166.0,
          height: 190.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
