import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinedb1e2/widgets/Box2Widget1.dart';
import 'package:flutterapp/figma/undefinedb1e2/widgets/CheckBMIWidget.dart';
import 'package:flutterapp/figma/undefinedb1e2/widgets/Back4Widget.dart';
import 'package:flutterapp/figma/undefinedb1e2/widgets/Box1Widget.dart';
import 'package:flutterapp/figma/undefinedb1e2/widgets/DoctorTipsWidget.dart';
import 'package:flutterapp/figma/undefinedb1e2/widgets/Nurseee1Widget.dart';
import 'package:flutterapp/figma/undefinedb1e2/widgets/EvaarrowiosbackfillWidget1.dart';

/* Frame general
    Autogenerated by FlutLab FTF Generator
  */
class Undefinedb1e2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 188, 178, 247),
            ),
            child: null,
          ),
          Positioned(
            left: -25.0,
            top: -106.0,
            right: null,
            bottom: null,
            width: 466.0,
            height: 830.0,
            child: Back4Widget(),
          ),
          Positioned(
            left: 5.0,
            top: 12.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: EvaarrowiosbackfillWidget1(),
          ),
          Positioned(
            left: 66.0,
            top: 43.0,
            right: null,
            bottom: null,
            width: 247.0,
            height: 320.0,
            child: Nurseee1Widget(),
          ),
          Positioned(
            left: 101.0,
            top: 394.0,
            right: null,
            bottom: null,
            width: 158.0,
            height: 69.0,
            child: Box2Widget1(),
          ),
          Positioned(
            left: 101.0,
            top: 486.0,
            right: null,
            bottom: null,
            width: 158.0,
            height: 68.0,
            child: Box1Widget(),
          ),
          Positioned(
            left: 116.0,
            top: 421.0,
            right: null,
            bottom: null,
            width: 122.0,
            height: 16.0,
            child: CheckBMIWidget(),
          ),
          Positioned(
            left: 107.0,
            top: 512.0,
            right: null,
            bottom: null,
            width: 140.0,
            height: 16.0,
            child: DoctorTipsWidget(),
          )
        ]),
      ),
    ));
  }
}
