import 'package:flutter/material.dart';

/* Rectangle back 1
    Autogenerated by FlutLab FTF Generator
  */
class Back1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(50.0),
      child: Container(
        width: 515.0,
        height: 714.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(50.0),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(50.0),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Image.asset(
                  "assets/images/2e1404f5f0c30764a9c2890fec4d371f905debbd.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 515.0,
                  height: 714.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
                Image.asset(
                  "assets/images/2e1404f5f0c30764a9c2890fec4d371f905debbd.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 515.0,
                  height: 714.0,
                  colorBlendMode: BlendMode.dstATop,
                )
              ]),
        ),
      ),
    );
  }
}
