import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector box2
    Autogenerated by FlutLab FTF Generator
  */
class Box2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 178.0,
      height: 74.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 20C0 8.95431 8.95431 0 20 0L158 0C169.046 0 178 8.9543 178 20L178 54C178 65.0457 169.046 74 158 74L20 74C8.9543 74 0 65.0457 0 54L0 20Z')
          ..color = Color.fromARGB(255, 244, 151, 201),
        SvgPathPainter.stroke(
          1.0,
          strokeMiterLimit: null,
          strokeCap: null,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M20 1L158 1L158 -1L20 -1L20 1ZM177 20L177 54L179 54L179 20L177 20ZM158 73L20 73L20 75L158 75L158 73ZM1 54L1 20L-1 20L-1 54L1 54ZM20 73C9.50659 73 1 64.4934 1 54L-1 54C-1 65.598 8.40202 75 20 75L20 73ZM177 54C177 64.4934 168.493 73 158 73L158 75C169.598 75 179 65.598 179 54L177 54ZM158 1C168.493 1 177 9.50659 177 20L179 20C179 8.40202 169.598 -1 158 -1L158 1ZM20 -1C8.40202 -1 -1 8.40202 -1 20L1 20C1 9.50659 9.50659 1 20 1L20 -1Z')
          ..color = Color.fromARGB(255, 0, 0, 0),
      ]),
    );
  }
}
