import 'package:flutter/material.dart';

/* Rectangle cardido 1
    Autogenerated by FlutLab FTF Generator
  */
class Cardido1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 51.0,
      height: 44.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/3364ce159fdde5c1e7dcc2e0f29297e6e0f69347.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/3364ce159fdde5c1e7dcc2e0f29297e6e0f69347.png",
          color: null,
          fit: BoxFit.cover,
          width: 51.0,
          height: 44.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
