import 'package:flutter/material.dart';

/* Text DOCTORS TIPS
    Autogenerated by FlutLab FTF Generator
  */
class DOCTORSTIPSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''DOCTORS TIPS''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 20.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
