import 'package:flutter/material.dart';

/* Rectangle download 1
    Autogenerated by FlutLab FTF Generator
  */
class Download1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 51.0,
      height: 51.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/7bcff8ae25d4cd61a96056f76ab514bd1b12891b.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/7bcff8ae25d4cd61a96056f76ab514bd1b12891b.png",
          color: null,
          fit: BoxFit.cover,
          width: 51.0,
          height: 51.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
