import 'package:flutter/material.dart';

/* Rectangle eye 1
    Autogenerated by FlutLab FTF Generator
  */
class Eye1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-1.00, 0.00, 0.00, 0.00, 0.00, 1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 51.0,
          height: 47.0,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: ExactAssetImage(
                "assets/images/8ededa52a9c45ec236fcb80700dfc2fedd1433c3.png",
              ),
              fit: BoxFit.cover,
            ),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Image.asset(
              "assets/images/8ededa52a9c45ec236fcb80700dfc2fedd1433c3.png",
              color: null,
              fit: BoxFit.cover,
              width: 51.0,
              height: 47.0,
              colorBlendMode: BlendMode.dstATop,
            ),
          ),
        ));
  }
}
