import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Rectangle 23
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 316.0,
      height: 380.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          ),
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 20C0 8.9543 8.95431 0 20 0L296 0C307.046 0 316 8.95431 316 20L316 360C316 371.046 307.046 380 296 380L20 380C8.9543 380 0 371.046 0 360L0 20Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
