import 'package:flutter/material.dart';

/* Rectangle ut 1
    Autogenerated by FlutLab FTF Generator
  */
class Ut1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 51.0,
      height: 47.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/fd8067046090c5f2475cb4e3ef45341f69e18d3c.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/fd8067046090c5f2475cb4e3ef45341f69e18d3c.png",
          color: null,
          fit: BoxFit.cover,
          width: 51.0,
          height: 47.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
