import 'package:flutter/material.dart';

/* Rectangle va 1
    Autogenerated by FlutLab FTF Generator
  */
class Va1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 47.0,
      height: 48.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/d5caf36787099e03b85bfad4f4d06b2519c51bb7.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/d5caf36787099e03b85bfad4f4d06b2519c51bb7.png",
          color: null,
          fit: BoxFit.cover,
          width: 47.0,
          height: 48.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
